name: Speak-Shine Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4

        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t speak-shine .

      - name: Tag Docker Image
        run: |
          docker tag speak-shine:latest \
          ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:latest

      - name: Push Docker Image to Amazon ECR
        run: |
          docker push \
          ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:latest

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}

          script: |

            cd ~/Speak-Shine-

            echo "================================="
            echo "Pull latest GitHub code"
            echo "================================="

            git pull origin main

            echo "================================="
            echo "Backup docker compose"
            echo "================================="

            cp docker-compose.yml docker-compose.backup.yml

            echo "================================="
            echo "Login to AWS ECR"
            echo "================================="

            aws ecr get-login-password --region ap-south-1 | \
            docker login --username AWS --password-stdin \
            284187934444.dkr.ecr.ap-south-1.amazonaws.com

            echo "================================="
            echo "Stopping old containers"
            echo "================================="

            docker compose down

            echo "================================="
            echo "Pull latest Docker image"
            echo "================================="

            docker pull \
            284187934444.dkr.ecr.ap-south-1.amazonaws.com/speak-shine:latest

            echo "================================="
            echo "Start updated containers"
            echo "================================="

            docker compose up -d

            echo "================================="
            echo "Waiting for health check"
            echo "================================="

            sleep 20

            echo "================================="
            echo "Checking deployment status"
            echo "================================="

            if docker ps | grep speak-shine-app; then

              echo "================================="
              echo "Deployment successful"
              echo "================================="

            else

              echo "================================="
              echo "Deployment failed"
              echo "Rolling back..."
              echo "================================="

              docker compose down

              cp docker-compose.backup.yml docker-compose.yml

              docker compose up -d

              exit 1

            fi

            echo "================================="
            echo "Running Containers"
            echo "================================="

            docker ps

            echo "================================="
            echo "Deployment Completed"
            echo "================================="   

# name: Speak-Shine Deployment

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Deploy to AWS EC2
#         uses: appleboy/ssh-action@master

#         with:
#           host: ${{ secrets.HOST }}
#           username: ${{ secrets.USERNAME }}
#           key: ${{ secrets.SSH_KEY }}

#           script: |
#             cd ~/Speak-Shine-

#             git pull origin main

#             npm install

#             pm2 restart speak-shine